[package]
name = "dkalc"
version = "0.6.0"
authors = ["Hadrien Nilsson <hadrien@psydk.org>"]

[dependencies.gtk]
version = "0.5.0"
features = ["v3_20"]

[dependencies.gio]
version = "0.5.0"

[dependencies.glib]
version = "0.6.0"
